


### 前端文章获取
GET http://localhost:5000/Articles HTTP/1.1

### 48小时阅读排行
GET http://localhost:5000/Articles/TheFirstReadCount HTTP/1.1

### 10天点赞排行
GET http://localhost:5000/Articles/TheTenPraiseCount HTTP/1.1

### 10天评论排行
GET http://localhost:5000/Articles/TheTenTalkCount HTTP/1.1

### 前端文章实体获取
GET http://localhost:5000/Articles/ArticleTexts/1 HTTP/1.1

### 前端获取文章评论
GET http://localhost:5000/ArticleTalks/5 HTTP/1.1

### 添加评论
POST http://localhost:5000/ArticleTalks/addTalk HTTP/1.1
Content-Type: application/json

{
   "UserId" : "5",
   "ArticleId" : "5",
   "ATtext":"这是你大爷"
}

### 删除评论
DELETE http://localhost:5000/ArticleTalks/deleteTalk/11 HTTP/1.1

### 是否点赞
GET http://localhost:5000/ArticleAPraises/1/6 HTTP/1.1

### 点赞
POST http://localhost:5000/ArticleAPraises/addPraises HTTP/1.1
Content-Type: application/json

{
   "UserId" : "3",
   "ArticleId" : "6"
}

### 访问
POST http://localhost:5000/ArticleReads/addRead HTTP/1.1
Content-Type: application/json

{
   "UserId" : "4",
   "ArticleId" : "3"
}


### 登录
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
   "UName" : "User",
   "Upassword" : "113"
}

### 注册
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
   "UName" : "11111",
   "Upassword" : "1",
   "reUpassword" : "1",
   "MatterId" : "1",
   "MKey" : "测试"
}

### 修改密码
put http://localhost:5000/users/changePwd/1 HTTP/1.1
Content-Type: application/json

{
   "inUpassword":"111",
   "Upassword" : "111",
   "reUpassword" : "111"
}

### 忘记密码问题获取
GET http://localhost:5000/users/ForgetPwdMatters/Action HTTP/1.1

### 忘记密码修改密码
put http://localhost:5000/users/ForgetPwd/6 HTTP/1.1
Content-Type: application/json

{
   "MKey":"测试",
   "Upassword" : "1877",
   "reUpassword" : "1877"
}

### 获取密保问题
GET http://localhost:5000/matters HTTP/1.1

### 获取当前用户信息
GET http://localhost:5000/UserInfos/1 HTTP/1.1

### 修改用户信息
PUT http://localhost:5000/UserInfos/ChangeUserInfo/2 HTTP/1.1
Content-Type: application/json

{
   "NickName":"666",
   "Sex":"男"
}

### 后台登录
POST http://localhost:5000/BackUser/login HTTP/1.1
Content-Type: application/json

{
   "UName" : "User",
   "Upassword" : "113"
}

### 后台添加问题
POST http://localhost:5000/BackMatter/AddMatter HTTP/1.1
Content-Type: application/json

{
   "MName" : "我的喜欢11012？"
}

### 后台修改问题
PUT http://localhost:5000/BackMatter/Changematter/6 HTTP/1.1
Content-Type: application/json

{
   "MName" : "666"
   
}

### 删除问题
DELETE http://localhost:5000/BackMatter/deleteMatter/4 HTTP/1.1

### 问题模糊查询
GET http://localhost:5000/BackMatter/likeMname/？ HTTP/1.1

### 后台获取所有权限
GET  http://localhost:5000/BackPowers HTTP/1.1

### 后台添加权限
POST http://localhost:5000/BackPowers/AddPower HTTP/1.1
Content-Type: application/json

{
   "PName" : "超级用户"
}

### 后台修改权限
PUT http://localhost:5000/BackPowers/ChangePowers/1 HTTP/1.1
Content-Type: application/json

{
   "PName" : "超级"
   
}

### 删除权限
DELETE http://localhost:5000/BackPowers/deletePower/4 HTTP/1.1

### 权限模糊查询
GET http://localhost:5000/BackPowers/likePower/用 HTTP/1.1


### 后台获取用户数据
GET  http://localhost:5000/BackUser HTTP/1.1

### 后台修改用户数据
PUT http://localhost:5000/BackUser/ChangeuserInfo/4 HTTP/1.1
Content-Type: application/json

{
   "UName":"ssffyy",
   "Upassword":"110",
   "PowerId":"1",
   "MatterId":"3",
   "MKey":"我不想报错",
   "NickName":"无敌啊",
   "Sex":"女",
   "Remarks":"见证奇迹"
}

### 后台添加用户数据
POST http://localhost:5000/BackUser/adduserInfo HTTP/1.1
Content-Type: application/json

{
   "UName":"s996",
   "Upassword":"110",
   "PowerId":"1",
   "MatterId":"3",
   "MKey":"我不想报错",
   "NickName":"无敌啊",
   "Sex":"女",
   "Remarks":"见证奇迹"
}

### 删除用户信息
DELETE http://localhost:5000/BackUser/deleteuserInfo/7 HTTP/1.1

### 模糊查询用户昵称
GET http://localhost:5000/BackUser/likeNickName/管 HTTP/1.1

### 后台文章获取
GET http://localhost:5000/BackArticle HTTP/1.1

### 用户点赞详情（文章Id)
GET http://localhost:5000/BackArticle/APraiseUser/1 HTTP/1.1

### 用户访问详情（文章Id)
GET http://localhost:5000/BackArticle/AReadUser/1 HTTP/1.1

### 用户评论详情（文章Id)
GET http://localhost:5000/BackArticle/ATalkUser/1 HTTP/1.1

### 删除用户访问详情（访问Id)
DELETE http://localhost:5000/BackArticle/deleteReadUser/2 HTTP/1.1

### 删除用户评论详情（评论Id)
DELETE http://localhost:5000/BackArticle/deleteTalkUser/2 HTTP/1.1

### 删除用户评论详情（评论Id)
DELETE http://localhost:5000/BackArticle/deleteAPraiseUser/2 HTTP/1.1

### 删除文章以及关联信息
DELETE http://localhost:5000/BackArticle/deleteArticle/2 HTTP/1.1

















###
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyNzY5OTA1NCwiaXNzIjoiV29vWiJ9.8UNhkugcqN1L0Lx-qrgvtvi3yrYmEef3OJiL6hDYtrs",
    "refreshtoken":"113"
}

### 测试审计日志
GET http://localhost:5000/AutidInfo/2 HTTP/1.1

