
###

GET http://localhost:5000/UserInfos HTTP/1.1

###查询
GET http://localhost:5000/users HTTP/1.1


### 添加
POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
   "UName":"Action",
   "Upassword":"123",
   "PowerId" : "1",
   "MatterId" : "2",
   "UEmail":"112358@qq.com",
   "MKey" : "春天"
}

### 修改
PUT http://localhost:5000/users/5 HTTP/1.1
Content-Type: application/json

{
   "UName":"Action",
   "Upassword":"556", 
   "UEmail":"112358@qq.com",
   "MKey" : "秋天"
}

### 删除
DELETE http://localhost:5000/users/3 HTTP/1.1



