### 前端文章获取
GET http://localhost:5000/Articles HTTP/1.1

### 登录
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
   "UName" : "User",
   "Upassword" : "1134"
}


### 注册
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
   "UName" : "1",
   "Upassword" : "1",
   "reUpassword" : "1",
   "MatterId" : "1",
   "MKey" : "测试"
}

### 修改密码
put http://localhost:5000/users/changePwd/6 HTTP/1.1
Content-Type: application/json

{
   "inUpassword":"113",
   "Upassword" : "111",
   "reUpassword" : "111"
}

### 忘记密码问题获取
GET http://localhost:5000/users/ForgetPwdMatters/Action HTTP/1.1

### 忘记密码修改密码
put http://localhost:5000/users/ForgetPwd/6 HTTP/1.1
Content-Type: application/json

{
   "MKey":"测试",
   "Upassword" : "1877",
   "reUpassword" : "1877"
}

### 获取密保问题
GET http://localhost:5000/matters HTTP/1.1

### 刷新重新获取token
POST http://localhost:5000/users/refreshtoken HTTP/1.1
Content-Type: application/json

### 获取当前用户信息
GET http://localhost:5000/UserInfos/6 HTTP/1.1

### 创建用户信息
POST http://localhost:5000/UserInfos/newUserInfo/6 HTTP/1.1
Content-Type: application/json

{
   "NickName":null,
   "Sex":null
}

### 修改用户信息
PUT http://localhost:5000/UserInfos/ChangeUserInfo/6 HTTP/1.1
Content-Type: application/json

{
   "NickName":"666",
   "Sex":"男"
}

### 后台登录

POST http://localhost:5000/BackUser/login HTTP/1.1
Content-Type: application/json

{
   "UName" : "User",
   "Upassword" : "113"
}

###
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTYyNzY5OTA1NCwiaXNzIjoiV29vWiJ9.8UNhkugcqN1L0Lx-qrgvtvi3yrYmEef3OJiL6hDYtrs",
    "refreshtoken":"113"
}

### 测试审计日志
GET http://localhost:5000/AutidInfo/2 HTTP/1.1

